name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build --file Dockerfile --tag bardolphshampine77769/nginx-web-server:$git_hash .
      
      
    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        #registry: 
        username: bardolphshampine77769
        password: ${{ secrets.DOCKER_TOKEN }}
        # Specifies whether the given registry is ECR (auto, true or false)
        ecr: auto
        logout: true
        
    - name: Docker push    
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "Pushing image to Docker Hub..."
        docker push bardolphshampine77769/nginx-web-server:$git_hash
        echo "::set-output name=image::bardolphshampine77769/nginx-web-server:$git_hash"

    - name: Update Version
      run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          tag=$(cat ./charts/web-server/values.yaml | grep tag: | awk '{print $2}')
          sed -i "s/$tag/$git_hash/" ./charts/web-server/values.yaml
          
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@v0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: Version updated
